import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import BackgroundShowcase from "@/components/BackgroundShowcase";

export const metadata: Metadata = {
  title:
    "NEO MeTRO CITY - the most geeky UI Components Library & Effects for Tailwind CSS.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Kosugi+Maru&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Quicksand:wght@300..700&family=Zen+Kaku+Gothic+New:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-quicksand w-full min-h-screen overflow-x-hidden">
        <BackgroundShowcase />
        <Header />
        <div className="relative">{children}</div>
        <input id="side-drawer" type="checkbox" className="drawer-toggle" />
        <div className="drawer-left">
          <label htmlFor="side-drawer" className="drawer-overlay" />
          <div className="menu min-h-full w-80 bg-cyber-black neon-border-r-orange p-4">
            <ul className="uppercase">
              <li>Components</li>
              <li>Item 2</li>
              <li>Item 3</li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
